services:
  - name: users
    url: "http://localhost:9002"
    health_check: "/health"
    internal_prefix: "/users/internal"
    internal_whitelist:
      - "127.0.0.1"

  - name: applications
    url: "http://localhost:9003"
    health_check: "/health"
    internal_prefix: "/applications/internal"
    internal_whitelist:
      - "127.0.0.1"

