#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 <server_name>"
    exit 1
fi

SERVER_NAME="$1"
BASIC_BASE64=$(
  (printf "%s:" "$SERVER_NAME";openssl rand 32) | openssl base64 -A
)

# Хешируем итоговую base64 строку
HASH=$(printf "%s" "$BASIC_BASE64" | openssl dgst -sha256 | awk '{print $2}')

echo "Server_name: $SERVER_NAME"
echo "Basic_token: $BASIC_BASE64"
echo "SHA256_hash: $HASH"
