daemon off; 

error_log /dev/stderr warn;
pid /dev/null; 

events {
    worker_connections 1024;
}

http {
    error_log /dev/stderr warn;
    access_log /dev/stdout;

    lua_shared_dict app 1m;

    lua_package_path "lua/?.lua;;";

    init_by_lua_file "lua/init_app.lua";
    server {
        listen 8080;
        server_name localhost;
        lua_code_cache off;

        location / {
            content_by_lua_file "lua/my_endpoint.lua";
        }
    }
}
